version: "3"
services:
  tplays:
    build:
      context: .
      args:
        COUNTRY_CODE: ${COUNTRY_CODE}
        DISPLAY: ${DISPLAY}
    environment:
      - CHANNEL=${CHANNEL}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
      - GAME_FILE=${GAME_FILE}
    shm_size: "2gb"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./twitch-plays:/home/user/twitch-plays
      - ./archive:/home/user/archive
      - local:/home/user/.local
      - /tmp/.X11-unix:/tmp/.X11-unix
volumes:
  local:
